### ISSUE TITLE
Missing 20.04 PPA repo

### ISSUE THREAD

**Issue by gnomed** [mumble-voip/mumble-ubuntu-ppa#13] opened 2020-06-25 06:50 UTC
When adding the PPA repository on Ubuntu 20.04 (the latest LTS version, Focal Fossa) an error occurs because the correct published index/metadata is [missing from the PPA](https://launchpad.net/~mumble/+archive/ubuntu/release/+index) for Focal Fossa. It can be worked around by forcing the PPA to use the `Eoan` codename instead of `Focal` but I'm hoping this can be an easy ask to get it updated.

Thanks for the hard work on a good service.

**Comment by Kissaki** [comment] 2020-06-27 16:02
Duplicate of #11 

It’s not that it is more complicated than before, but that an MR was merged with no context information of whether it intends to implement it, does implement it or partially implement it. And the effort is considerable enough that I will not put in that effort if it may already be fixed. But I did not receive an answer on #11 about that state or intention.

There is a chance the next release (version 1.3.2) will provide it. If not I may look into it again.

**Closed by Kissaki** 2020-06-27 16:02 UTC
